#!/usr/bin/env python
###############################################################################
#
# rnafold2list.py - Convert Vienna RNA package RNAfold -p PostScript output
#                   containing sequence and base pair probability matrix
#                   to a simple list format for use in the C bpalign program.
#
#
# File:    rnafold2list.py
# Author:  Alex Stivala
# Created: June 2007
#
# $Id: rnafold2list.py 277 2007-06-16 02:53:19Z astivala $
#
#
# Usage: rnafold2list.py <input-ps-file>
#
#   output is to stderr
#
# This script uses the functions in the readrnafold.py (q.v.) module to
# parse PostScript (_dp.ps file)
# generated by Vienna RNA package RNAfold -p program
# and output it in a simple list format for use as input to the C bpalign
# program. The format is as follows:
#
#   The first line is two integers separeated by whitespace
#   n m
#   where n is the length of the sequence and m is the number of base pairs
#   listed.
#   The second line is the sequence as a string of A,U,C,G charcters (terminated
#   by newline). Regardless of sequence length it is all on one line (of length
#   n)
#   Each subsequent line (of which there are m) is of the form:
#   i j p
#   where i and j are integers denoting two base pairs (starting from 0)
#   that are paired with probability p. p is floating point number in printf
#   %d format.
#   Lines starting with '#' in column 1 are comments.
#
###############################################################################

import sys

from readrnafold import *


#-----------------------------------------------------------------------------
#
# Function definitions
#
#-----------------------------------------------------------------------------

def usage(progname):
    """
    Print usage message and exit.
    """
    sys.stderr.write("Usage: " + progname + " filename_dp.ps\n")
    sys.exit(1)

#-----------------------------------------------------------------------------
#
# Main
#
#-----------------------------------------------------------------------------
    
def main():
    """
    main for rnafold2list

    Usage: rnafold2list.py <input-ps-filename>

    Convert Vienna RNA package RNAfold -p PostScript output in the supplied
    filename (_dp.ps file)
    containing sequence and base pair probability matrix
    to a simple list format for use in the C bpalign program.
    Output is to stdout.
    """

    if len(sys.argv) == 2:
        infilename = sys.argv[1]
    else:
        usage(sys.argv[0])
        
    (pairlist,sequence) = read_RNAfold_dotplot(infilename)
    # TODO: handle exceptions; doesn't really matter, will get error this way

    pairlist.sort() # ensure sorted by i and within that j ; actually is
                    # sorted that way by RNAfold anyway apparently but can't
                    # hurt to be sure.
    sys.stdout.write("# extracted from file %s by rnafold2list.py $Revision: 277 $\n" %
                     (infilename))
                     
    sys.stdout.write("%d %d\n" % (len(sequence), len(pairlist)))
    sys.stdout.write(sequence)
    sys.stdout.write('\n')
    for (i, j, p) in pairlist:
        sys.stdout.write("%d %d %f\n" % (i, j, p))
    

    
if __name__ == "__main__":
    main()
